[package]
name = "erlang-term"
version = "0.1.0"
authors = ["Thomas <thomastimmer11@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
num-bigint = "*"
num-traits = "*"
multimap = "0.8.1"