[package]
name = "erlang-term"
version = "0.1.0"
authors = ["Thomas <thomastimmer11@hotmail.com>"]
edition = "2018"
description = "Library to convert Erlang External Term Format to Rust objects, without using erlang NIFs."
keywords = ["erlang", "elixir", "serde"]
categories = ["encoding", "parser-implementations"]
repository = "https://github.com/thomas9911/erlang-term"
license = "Unlicense"

[dependencies]
nom = "*"
num-bigint = "*"
num-traits = "*"
keylist = "0.1"
serde = {version = "*", optional = true}
serde_derive = {version = "*", optional = true}
serde_json = {version = "*", optional = true}

[dev-dependencies]

[features]
serde_impl = ["serde", "serde_derive", "serde_json", "keylist/serde", "num-bigint/serde"]
