[package]
name = "rustlertest"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rustlertest"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
erlang-term = {path = "../../../", features = ["rustler"]}
